### PR TITLE
Add German Accents

### PR DESCRIPTION
**Pull request by tobiasgrosser**

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
This is just a minor contribution, but one needs to get started somehow.

Btw. this plugin works great for me. Thanks for your work (and the very useful documentation hidden in a resolved bug report).

**Comment by giltho** [comment]
Ok so people are actually using this, I'm gonna clean the codebase a tiny bit and try to write a start of a proper readme.
Thank you for your contribution !!!!

**Comment by giltho** [comment]
@tobiasgrosser Just published [version `0.0.3` on npm](https://www.npmjs.com/package/gatsby-transformer-bibtex) that contains your changes and an actual readme :)
Thanks again

**Comment by tobiasgrosser** [comment]
> @tobiasgrosser Just published [version `0.0.3` on npm](https://www.npmjs.com/package/gatsby-transformer-bibtex) that contains your changes and an actual readme :)
> Thanks again

Amazing. The new README provides exactly the information I needed! (I figured it out myself, but it will be super useful for future users)

**Comment by tobiasgrosser** [comment]
@giltho, thanks a lot for the super-fast response. I opened a couple of feature requests that list the features I am personally using on grosser.es as well as spcl.inf.ethz.ch. These are the last missing pieces to get my bibliography fully moved to gatsby.

**Comment by giltho** [comment]
My pleasure :) I've added all the features you asked for now, if anything else, don't hesitate to ask I'll see what I can do, or write a PR yourself if I'm in a day where it's harder for me to be responsive :)

**Comment by tobiasgrosser** [comment]
Wow, you are very quick!

I tested all of them and updated the corresponding issues. I also found a couple minor extensions that I would potentially use in the future.

Finally, I am not 100% certain, but I feel https://www.gatsbyjs.com/dashboard is not handling dependencies to unpacked packages well. I am not certain, but it seems I cannot use these new features before your next release. Hence, I would appreciate if you could spin another release (hoping this is not too hard).

Also, I realized you do not 'git tag' your releases. This might be a good idea.

**Pull request merged**
