### PR TITLE
Add note and school fields

### PR DESCRIPTION
**Pull request by tobiasgrosser**

### CODE REVIEW

**Comment by giltho** [comment]
I chose a different path that's more general and shouldn't need any more fields added. It works for me, it would be great to have your feedback :)
See last commit

**Comment by giltho** [comment]
If you validate that it gets you every field you need (in particular, I removed the `type` clash from #7), I'll push 0.1.0 :)
I did tag the `0.0.3` when I published it but I did it from the git cli and forgot to push the tag 😅

**Comment by tobiasgrosser** [comment]
I now get:
```
There was an error in your GraphQL query:

Cannot query field "allReference" on type "Query".

If you don't expect "allReference" to exist on the type "Query" it is most likely a typo.
However, if you expect "allReference" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allReference" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src/pages/publications.js:65:13

failed extract queries from components - 0.277s
```

This is the same error I got on the gatsbyjs.com cloud. Not sure why. It seems the bibtex transform is not generating any references. No idea how to debug this nicely.

I added you to my repo, in case you wanna try it yourself.

**Comment by giltho** [comment]
That is surprising indeed, I don't really see how this is happening, let me check your repo :)

**Comment by giltho** [comment]
@tobiasgrosser ok there's something wrong with the way npm fetches the dependencies on github.

I managed to get it to create the reference by running replacing
```json
"gatsby-transformer-bibtex": "giltho/gatsby-transformer-bibtex"
```
with
```json
"gatsby-transformer-bibtex": "file:../gatsby-transfomer-bibtex"
```
I'm guessing that once it's published you won't have the issue anymore
I'm publishing the `0.1.0` and will add patches if things are still missing

**Comment by giltho** [comment]
Oh god no, I found the actual mistake
It's not npm's fault really
the npm build command is wrong :/
it should be `npm run-script build` instead

yarn doesn't need the `run-script` part to run scripts

**Comment by giltho** [comment]
(it worked locally because I had already built it on my machine...)

**Comment by giltho** [comment]
`0.1.1` or the last commit should be working now

**Comment by tobiasgrosser** [comment]
I now get:

```
"gatsby-transformer-bibtex" threw an error while running the onCreateNode lifecycle:

entry.getYoutubeId is not a function

  114 | 
  115 |   var date = (entry.getFieldAsString('issue_date') ? entry.getFieldAsString('issue_date') : entry.getFieldAsString('year')).toString();
> 116 |   var youtubeId = entry.getFieldAsString('youtubeId') ? entry.getFieldAsString('youtubeId') : entry.getYoutubeId(entry.getFieldAsString('youtube'));
      |                                                                                                     ^
  117 |   var entry_type = entry.type;
  118 |   var ret = {};
  119 |   Object.keys(entry.fields).forEach(function (k) {
```

**Comment by tobiasgrosser** [comment]
> Oh god no, I found the actual mistake
> It's not npm's fault really
> the npm build command is wrong :/
> it should be `npm run-script build` instead
> 
> yarn doesn't need the `run-script` part to run scripts

Sorry for introducing this bug. :-(

**Comment by giltho** [comment]
No worry, I'm more happy about the fact that you wrote a PR than the fact it had a small bug

it's right to complain, it's plain wrong... I should definitely write tests to catch these things
I updated it on master, I'm not gonna publish the patch yet
Let's publish when it's working for you

**Comment by tobiasgrosser** [comment]
OK, this now seems to work for me. (Even though I cannot test it perfectly, as gatsbyjs.com only works for released packages). I think we are safe to do another release. Thanks so much for your work!

**Comment by giltho** [comment]
Published :)

**Comment by tobiasgrosser** [comment]
Perfect. All works and my publication list is beautifully formatted. Thanks so much!

**Comment by giltho** [comment]
Happy that it works !

**Pull request closed without merging**
