### PR TITLE
Add date as possible source field for date attribute

### PR DESCRIPTION
**Pull request by konstantinruge**
Can we add `date` as a possible field to populate the date attribute? I have a particular use-case where we use *date* instead of *issue_date* or *year*. And I guess that probably more people want to be able to use *date* as a field name 😊

### CODE REVIEW

**Comment by giltho** [comment]
Sorry, I somehow opened the notification and forgot to mark it an unread again.
Thank! I'm publishing that tonight when I can access my personal computer :)

**Comment by konstantinruge** [comment]
@giltho No worries and thanks for merging! Would be great if the updated version will be released soon? 😄

**Comment by giltho** [comment]
Done! Sorry again 😓

**Comment by konstantinruge** [comment]
Great thanks a lot 😄

**Pull request merged**
